export { AboutPage } from "./pages/AboutPage.jsx";
export { CitiesPage } from "./pages/CitiesPage.jsx";
export { CityPage } from "./pages/CityPage.jsx";
export { ContactPage } from "./pages/ContactPage.jsx";
export { LegalPage } from "./pages/LegalPage.jsx";
export { NotFoundPage } from "./pages/NotFoundPage.jsx";
export { PageHero } from "./pages/PageHero.jsx";
export { ToursPage } from "./pages/ToursPage.jsx";
export { UmutEkerPage } from "./pages/UmutEkerPage.jsx";
